# b) Podemos considerar o resultado final da variável x como o tamanho da lista? Justifique.

'''
SIM, NESSE CASO O VALOR FINAL DE x COINCIDE COM O TAMANHO DA LISTA, QUE É 3. PORÉM, ISSO
ACONTECE PORQUE O NÚMERO 3 FOI COLOCADO DIRETAMENTE NA CONDIÇÃO DO WHILE, MAS SE O NÚMERO 3
FOSSE SUBSTITUÍDO POR UMA VARIÁVEL, O RESULTADO FINAL DE x NÃO COINCIDIRIA COM O TAMANHO DA LISTA.

'''