# b) A alternativa anterior teve êxito? Justifique.

'''
NÃO TEVE ÊXITO TOTAL, O for É FEITO PARA REPETIÇÕES COM NÚMERO DEFINIDO/FINITO. A PRIMEIRA
REPETIÇÃO DO for É INDEFINIDA, POIS NÃO SABEMOS QUANTOS NÚMEROS O USUÁRIO VAI DIGITAR, POR ISSO,
USANDO O for NESSA SITUAÇÃO, OBRIGA EU CRIAR UM LIMITE DE REPETIÇÕES, O QUE NÃO SERIA IDEAL.

'''